<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>br.edu.iesb.tcc</groupId>
    <artifactId>selenium-tcc</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <packaging>jar</packaging>

    <name>selenium-tcc</name>
    <description>TCC - Automacao de testes E2E com Selenium WebDriver</description>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

        <selenium.version>4.47.0</selenium.version>
        <junit.version>6.1.0</junit.version>
        <surefire.version>3.5.2</surefire.version>
        <wdm.version>5.9.2</wdm.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>${selenium.version}</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <version>${junit.version}</version>
            <scope>test</scope>
        </dependency>

    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>${surefire.version}</version>
                <configuration>
                    <reportsDirectory>${project.basedir}/reports</reportsDirectory>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-report-plugin</artifactId>
                <version>${surefire.version}</version>
                <configuration>
                    <outputDirectory>${project.basedir}/reports/html</outputDirectory>
                    <outputName>index</outputName>
                    <reportsDirectories>
                        <reportsDirectory>${project.basedir}/reports</reportsDirectory>
                    </reportsDirectories>
                    <linkXRef>false</linkXRef>
                    <showSuccess>true</showSuccess>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
